# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'pim/grantleetheme' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/libkdepim' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'libraries/ktextaddons': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'plasma/plasma-activities': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
