# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'kde/pim/akonadi-mime' : '@latest'
    'kde/pim/grantleetheme' : '@latest'
    'kde/pim/kontactinterface' : '@latest'
    'kde/pim/kpimtextedit' : '@latest'
    'kde/pim/libkdepim' : '@latest'
    'kde/pim/libkleo' : '@latest'
    'kde/pim/messagelib' : '@latest'
    'kde/pim/pimcommon' : '@latest'
    'third-party/grantlee' : '@stable'
