# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'kde/pim/akonadi-mime' : '@same'
    'kde/pim/grantleetheme' : '@same'
    'kde/pim/kontactinterface' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/libkleo' : '@same'
    'kde/pim/messagelib' : '@same'
    'kde/pim/pimcommon' : '@same'
    'third-party/grantlee' : '@stable'
