# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'pim/akonadi-mime' : '@latest-kf6'
    'pim/grantleetheme' : '@latest-kf6'
    'pim/kontactinterface' : '@latest-kf6'
    'pim/kpimtextedit' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/messagelib' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
