/* config-akregator.h. Generated by cmake from config-akregator.h.cmake */
/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}
#cmakedefine WEBENGINEVIEWER_PRINT_SUPPORT 1
