version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "akregator"
SPDX-PackageSupplier = "Montel Laurent <montel@kde.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/pim/akregator"

[[annotations]]
path = ["README", "MAINTAINERS", "AUTHORS", "REUSE.toml", ".gersemirc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = ["README-pre-commit.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["CMakePresets.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Laurent Montel <montel@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"
