debian/tmp/usr/bin/akregator
debian/tmp/usr/lib/kde3/libakregatorpart.*
debian/tmp/usr/lib/libakregatorprivate.so.*
debian/tmp/usr/share/applnk/Internet/akregator.desktop
debian/tmp/usr/share/apps/akregator/*
debian/tmp/usr/share/apps/akregator/*/*
debian/tmp/usr/share/config.kcfg
debian/tmp/usr/share/config.kcfg/akregator.kcfg
debian/tmp/usr/share/icons/crystalsvg/scalable/apps/akregator.svgz
debian/tmp/usr/share/icons/*/*/*/*.png
debian/tmp/usr/share/services/akregator_part.desktop
debian/tmp/usr/share/services/feed.protocol
debian/overrides/akregator	/usr/share/lintian/overrides/
