.TH aKregator 1 "Mai 25, 2004"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
aKregator \- a KDE RSS Aggregator
.SH SYNOPSIS
.B aKregator
.RI "[ " generic-options " ] [ " URL " ]"
.br
.SH "DESCRIPTION"
.BR aKregator
is a KDE RSS aggregator with great look and feel.
.PP
.SH OPTIONS
.\" Below are aKregator-specific options.
For a full summary of options, run \fIakregator \-\-help\fP.
.SH AUTHOR
This manual page was written by Pierre Habouzit <pierre.habouzit@m4x.org>,
for the Debian GNU/Linux system (but may be used by others).
