/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.akregator.part.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef AKREGATORPARTADAPTOR_H_18801150461681
#define AKREGATORPARTADAPTOR_H_18801150461681

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.akregator.part
 */
class PartAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.akregator.part")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.akregator.part\" >\n"
"    <method name=\"openStandardFeedList\" />\n"
"    <method name=\"fetchFeedUrl\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"    </method>\n"
"    <method name=\"fetchAllFeeds\" />\n"
"    <method name=\"saveSettings\" />\n"
"    <method name=\"addFeedsToGroup\" >\n"
"      <arg direction=\"in\" type=\"as\" name=\"lst\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"feedname\" />\n"
"    </method>\n"
"    <method name=\"exportFile\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"    </method>\n"
"    <method name=\"addFeed\" />\n"
"  </interface>\n"
        "")
public:
    PartAdaptor(QObject *parent);
    virtual ~PartAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addFeed();
    void addFeedsToGroup(const QStringList &lst, const QString &feedname);
    void exportFile(const QString &url);
    void fetchAllFeeds();
    void fetchFeedUrl(const QString &url);
    void openStandardFeedList();
    void saveSettings();
Q_SIGNALS: // SIGNALS
};

#endif
